import PyQt5.QtGui
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from show_window import *
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2000, 1500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 2000, 1500))
        self.tabWidget.setStyleSheet("QTabBar::tab {\n"
                                     "    width: 665px; /* 更改Tab的宽度 */\n"
                                     "    height: 150px;\n"
                                     "    font-family: \"楷体\";\n"
                                     "    font-weight: bold;\n"
                                     "       font-size: 40px;"
                                     "}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_query = QtWidgets.QWidget()
        self.tab_query.setObjectName("tab_query")
        self.tableView = QtWidgets.QTableView(self.tab_query)
        self.tableView.setEnabled(True)
        self.tableView.setGeometry(QtCore.QRect(0, 300, 2000, 950))
        self.tableView.setLineWidth(0)
        self.tableView.setMidLineWidth(0)
        self.tableView.setIconSize(QtCore.QSize(0, 0))
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setHighlightSections(False)
        self.tableView.verticalHeader().setCascadingSectionResizes(False)
        self.tableView.horizontalHeader().setMinimumSectionSize(125)
        self.tableView.horizontalHeader().setMaximumSectionSize(125)
        self.tableView.horizontalHeader().setMaximumHeight(100)
        self.tableView.horizontalHeader().setMinimumHeight(100)
        model = PyQt5.QtGui.QStandardItemModel()
        columnHead = ["车次", "出发站", "到达站", "出发时间", "到达时间", "历时", "商务座特等座", "一等座", "二等座",
                      "高级软卧", "软卧", "动卧", "硬卧", "软座", "硬座", "无座"]
        model.setHorizontalHeaderLabels(columnHead)
        self.tableView.setModel(model)
        font = QFont("楷体", 12)
        self.tableView.horizontalHeader().setFont(font)
        self.tableView.horizontalHeader().setAlternatingRowColors(True)



        self.widget_checkBox = QtWidgets.QWidget(self.tab_query)
        self.widget_checkBox.setGeometry(QtCore.QRect(0, 150, 2000, 150))
        self.widget_checkBox.setObjectName("widget_checkBox")
        self.checkBox_G = QtWidgets.QCheckBox(self.widget_checkBox)
        self.checkBox_G.setGeometry(QtCore.QRect(500, 50, 340, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_G.setFont(font)
        self.checkBox_G.setObjectName("checkBox_G")
        self.checkBox_D = QtWidgets.QCheckBox(self.widget_checkBox)
        self.checkBox_D.setGeometry(QtCore.QRect(800, 50, 340, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_D.setFont(font)
        self.checkBox_D.setObjectName("checkBox_D")
        self.checkBox_Z = QtWidgets.QCheckBox(self.widget_checkBox)
        self.checkBox_Z.setGeometry(QtCore.QRect(1100, 50, 340, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_Z.setFont(font)
        self.checkBox_Z.setObjectName("checkBox_Z")
        self.checkBox_T = QtWidgets.QCheckBox(self.widget_checkBox)
        self.checkBox_T.setGeometry(QtCore.QRect(1400, 50, 340, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_T.setFont(font)
        self.checkBox_T.setObjectName("checkBox_T")
        self.checkBox_K = QtWidgets.QCheckBox(self.widget_checkBox)
        self.checkBox_K.setGeometry(QtCore.QRect(1700, 50, 340, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_K.setFont(font)
        self.checkBox_K.setObjectName("checkBox_K")
        self.label_type2 = QtWidgets.QLabel(self.widget_checkBox)
        self.label_type2.setGeometry(QtCore.QRect(150, 65, 270, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_type2.setFont(font)
        self.label_type2.setObjectName("label_type2")
        self.widget = QtWidgets.QWidget(self.tab_query)
        self.widget.setGeometry(QtCore.QRect(0, 0, 2000, 150))
        self.widget.setObjectName("widget")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(150, 50, 270, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(550, 50, 270, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(950, 50, 270, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(1500, 25, 250, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setGeometry(QtCore.QRect(310, 25, 240, 100))
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setFontPointSize(20)
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_2.setGeometry(QtCore.QRect(710, 25, 240, 100))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_2.setFontPointSize(20)
        self.textEdit_3 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_3.setGeometry(QtCore.QRect(1110, 25, 240, 100))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_3.setFontPointSize(20)
        self.tabWidget.addTab(self.tab_query, "")
        self.tab_analysis = QtWidgets.QWidget()
        self.tab_analysis.setObjectName("tab_analysis")
        self.tabWidget.addTab(self.tab_analysis, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2000, 110))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_G.setText(_translate("MainWindow", "GC-高铁"))
        self.checkBox_D.setText(_translate("MainWindow", "D-动车"))
        self.checkBox_Z.setText(_translate("MainWindow", "Z-直达"))
        self.checkBox_T.setText(_translate("MainWindow", "T-特快"))
        self.checkBox_K.setText(_translate("MainWindow", "K-特快"))
        self.label_type2.setText(_translate("MainWindow", "车次类型："))
        self.label_4.setText(_translate("MainWindow", "出发地："))
        self.label_5.setText(_translate("MainWindow", "目的地："))
        self.label_6.setText(_translate("MainWindow", "出发日："))
        self.pushButton.setText(_translate("MainWindow", "查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_query), _translate("MainWindow", "车票查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_analysis), _translate("MainWindow", "卧铺售票分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "车票起售时间"))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow1 = QMainWindow()  # MainWindow1随便改
    ui = Ui_MainWindow()  # 随便改
    ui.setupUi(MainWindow1)
    MainWindow1.show()
    ui.pushButton.clicked.connect(lambda: on_click(ui))
    sys.exit(app.exec_())

